####################################################################################################
##                                                                                                ##
##              .:                                                                                ##
##            :J#&5^                                                                              ##
##         :Y&@@@@@P!5GP:      ___ ___ ___ _  _                   ___        _                    ## 
##       ^5&@@@@@@@@@@@@^      | __/ __| _ \ || |___ _ __  ___ ___| _ \___ __(_)_ __  ___ ___     ##
##      ~P@@@@@@@@@@@@@@@J.    | _|\__ \  _/ __ / _ \ '  \/ -_)___|   / -_) _| | '_ \/ -_|_-<     ##
##    .P@@@@@@@@@@@@@@@@@@#~   |___|___/_| |_||_\___/_|_|_\___|   |_|_\___\__|_| .__/\___/__/     ##
##     ::B@@@@@@@@@@@@@@@!:.    Ready to use ESP32/8266 Templates for ESPHome  |_|                ##
##       B@@@@@@@@@@@@@@@^                                                                        ##
##       G@&&&&&&&&&&&&&&^      Board:   Sonoff Pow R2 (ESP8266)                                  ##
##       .::::::::::::::.       Version: 1.0-Beta                                                 ##
##                                                                                                ##
####################################################################################################

###### Device name ######
esphome:
  name: sonoff-pow-r2-template
  comment: Sonoff Pow R2 Template
  friendly_name: sonoff-pow-r2-template
 ### Project info ###  
  project:
    name: "JuanZagoR.SonoffPowR2Template"
    version: "1.0-Beta"

###### Dev board and platform ######
esp8266:
  board: sonoff_basic




###### Data logger ######
logger:
  baud_rate: 0
  level: VERBOSE
  
###### Home Assistant's Native API Config ######
api:
  encryption:
    key: !secret api_password
  
###### MQTT Broker Config ######
mqtt:
  discovery: false
  broker: !secret mqtt_broker
  port: !secret mqtt_brokerport
#  keepalive: 5s
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery_prefix: homeassistant
  
###### Over-the-Air Updates ######
ota:
  password: !secret ota_password




###### Network Config ######
wifi:
  networks:
    - ssid: !secret wifi_ssid
      bssid: !secret wifi_bssid
      password: !secret wifi_password

    - ssid: !secret wifi_ssid2
      bssid: !secret wifi_bssid2
      password: !secret wifi_password2

    - ssid: !secret wifi_ssid3
      bssid: !secret wifi_bssid3
      password: !secret wifi_password3

      #### Static IP Address ####
   # manual_ip:
   #   static_ip: 192.168.254.170
   #   gateway: 192.168.254.1
   #   subnet: 255.255.128.0
   #   dns1: 192.168.254.4
   #   dns2: 192.168.254.1

      #### Other settings ####
  #  fast_connect: on
  #  power_save_mode: none
  
###### Access Point and Captive Portal Config ######
  ap:
    ssid: "sonoff-pow-r2"
    password: !secret ap_password
  
captive_portal:
  



###### 'Ports' Config ######
  ### Status LED ###
status_led:
  pin: GPIO13

  ### UART Bus (Required to retrieve data from CSE7766) ###
uart:
  rx_pin: RX
  baud_rate: 4800





####### Sensors #######

  ### Binary Sensor (built-in button) ###
binary_sensor:
 - platform: gpio
   pin:
     number: GPIO0
     mode:
      input: true
      pullup: true
     inverted: true
   name: "Sonoff Pow R2 Button"
   on_press:
    - switch.toggle: relay
 - platform: status
   name: "Sonoff Pow R2 Status"

sensor:
  ### CSE7766 UART Serial Meter ###
 - platform: cse7766
   current:
     name: "Sonoff Pow R2 Current"
   voltage:
     name: "Sonoff Pow R2 Voltage"
   power:
     name: "Sonoff Pow R2 Power"
   energy:
     name: "Sonoff Pow R2 Energy"
   update_interval: 300ms

  ### Home Assistant Entities (through Native API) ###
 - platform: homeassistant
   id: home_assistant_entity_id
   entity_id: sensor.entity
#    attribute: current_power
  


switch:
  ### Built-in Relay ###
  - platform: gpio
    pin: GPIO12
    name: "Sonoff Pow R2 Relay"
    id: relay
    restore_mode: ALWAYS_ON
